version: '3.3'
services:
  keralolsavam-backend:
    container_name: keralolsavam-backend
    build:
      context: .
    environment:
      - VIRTUAL_HOST=dscblogs.mec.ac.in
    restart: "always"

networks:
  default:
    external:
      name: mec